import os
from pathlib import Path

import click

from ecs_utils import get_cluster_service_ips


def generate_ssh_config(
    mappings: dict[tuple[str, str], list[str]],
    *,
    user: str = "ec2-user",
    identity_file: str | None = None,
) -> str:
    """Generate SSH config content from cluster/service IP mappings."""
    lines = ["# Auto-generated by sync_ssh.py -- do not edit manually"]

    for (cluster, service), ips in sorted(mappings.items()):
        ip = ips[0]
        lines.append("")
        lines.append(f"Host {cluster}-{service}")
        lines.append(f"  HostName {ip}")
        lines.append(f"  User {user}")
        if identity_file:
            lines.append(f"  IdentityFile {identity_file}")

    lines.append("")
    return "\n".join(lines)


def ensure_include(config_path: str, hosts_path: str) -> None:
    """Ensure Include directive is at the top of SSH config."""
    include_line = f"Include {hosts_path}"
    path = Path(config_path)

    if path.exists():
        content = path.read_text()
        if include_line in content:
            return
        content = include_line + "\n" + content
    else:
        content = include_line + "\n"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


@click.command()
@click.option("--region", "-r", default="us-east-1", help="AWS region name")
@click.option("--profile", "-p", default=None, help="AWS profile name")
@click.option(
    "--private/--public", default=True, help="Use private IPs instead of public"
)
@click.option("--identity-file", "-i", default=None, help="SSH identity file path")
@click.option("--user", "-u", default="ec2-user", help="SSH user")
@click.option("--dry-run", is_flag=True, help="Print config without writing")
@click.option(
    "--hosts-file",
    default=os.path.expanduser("~/.ssh/ecs_hosts"),
    help="Path to the generated hosts file",
)
@click.option(
    "--ssh-config",
    default=os.path.expanduser("~/.ssh/config"),
    help="Path to SSH config file",
)
def cli(region, profile, private, identity_file, user, dry_run, hosts_file, ssh_config):
    """Sync ECS instance IPs to SSH config."""
    mappings = get_cluster_service_ips(region, profile, None, None, private)

    config_content = generate_ssh_config(
        mappings, user=user, identity_file=identity_file
    )

    if dry_run:
        click.echo(config_content)
        return

    Path(hosts_file).parent.mkdir(parents=True, exist_ok=True)
    Path(hosts_file).write_text(config_content)
    ensure_include(ssh_config, hosts_file)

    count = len(mappings)
    click.echo(f"Wrote {count} host(s) to {hosts_file}")


if __name__ == "__main__":
    cli()
