import os
import textwrap
from pathlib import Path
from unittest.mock import patch

import pytest
from click.testing import CliRunner

from sync_ssh import generate_ssh_config, ensure_include, cli


@pytest.fixture
def tmp_ssh_dir(tmp_path):
    ssh_dir = tmp_path / ".ssh"
    ssh_dir.mkdir()
    return ssh_dir


class TestGenerateSshConfig:
    def test_basic_output(self):
        mappings = {("web-staging", "nginx"): ["10.0.0.5"]}
        result = generate_ssh_config(mappings, user="ec2-user")

        assert "Host web-staging-nginx" in result
        assert "HostName 10.0.0.5" in result
        assert "User ec2-user" in result

    def test_header_comment(self):
        result = generate_ssh_config({}, user="ec2-user")
        assert "Auto-generated by sync_ssh.py" in result

    def test_multiple_services(self):
        mappings = {
            ("staging", "nginx"): ["10.0.0.1"],
            ("production", "nginx"): ["10.0.1.1"],
        }
        result = generate_ssh_config(mappings, user="ec2-user")

        assert "Host staging-nginx" in result
        assert "Host production-nginx" in result

    def test_picks_first_ip(self):
        mappings = {("web", "app"): ["10.0.0.1", "10.0.0.2"]}
        result = generate_ssh_config(mappings, user="ec2-user")

        assert "HostName 10.0.0.1" in result
        assert "10.0.0.2" not in result

    def test_custom_user(self):
        mappings = {("web", "app"): ["10.0.0.1"]}
        result = generate_ssh_config(mappings, user="ubuntu")

        assert "User ubuntu" in result

    def test_identity_file(self):
        mappings = {("web", "app"): ["10.0.0.1"]}
        result = generate_ssh_config(
            mappings, user="ec2-user", identity_file="~/.ssh/mykey.pem"
        )

        assert "IdentityFile ~/.ssh/mykey.pem" in result

    def test_no_identity_file_by_default(self):
        mappings = {("web", "app"): ["10.0.0.1"]}
        result = generate_ssh_config(mappings, user="ec2-user")

        assert "IdentityFile" not in result

    def test_empty_mappings(self):
        result = generate_ssh_config({}, user="ec2-user")
        assert "Auto-generated" in result
        assert "Host " not in result


class TestEnsureInclude:
    def test_adds_include_to_empty_config(self, tmp_ssh_dir):
        config_path = tmp_ssh_dir / "config"
        config_path.touch()
        hosts_path = tmp_ssh_dir / "ecs_hosts"

        ensure_include(str(config_path), str(hosts_path))

        content = config_path.read_text()
        assert f"Include {hosts_path}" in content

    def test_adds_include_to_existing_config(self, tmp_ssh_dir):
        config_path = tmp_ssh_dir / "config"
        config_path.write_text("Host myserver\n  HostName 1.2.3.4\n")
        hosts_path = tmp_ssh_dir / "ecs_hosts"

        ensure_include(str(config_path), str(hosts_path))

        content = config_path.read_text()
        lines = content.splitlines()
        assert lines[0] == f"Include {hosts_path}"
        assert "Host myserver" in content

    def test_idempotent(self, tmp_ssh_dir):
        config_path = tmp_ssh_dir / "config"
        config_path.write_text("Host myserver\n  HostName 1.2.3.4\n")
        hosts_path = tmp_ssh_dir / "ecs_hosts"

        ensure_include(str(config_path), str(hosts_path))
        ensure_include(str(config_path), str(hosts_path))

        content = config_path.read_text()
        assert content.count(f"Include {hosts_path}") == 1

    def test_creates_config_if_missing(self, tmp_ssh_dir):
        config_path = tmp_ssh_dir / "config"
        hosts_path = tmp_ssh_dir / "ecs_hosts"

        ensure_include(str(config_path), str(hosts_path))

        assert config_path.exists()
        assert f"Include {hosts_path}" in config_path.read_text()


class TestCliDryRun:
    @patch("sync_ssh.get_cluster_service_ips")
    def test_dry_run_prints_config(self, mock_get_ips):
        mock_get_ips.return_value = {
            ("web-staging", "nginx"): ["10.0.0.5"]
        }
        runner = CliRunner()
        result = runner.invoke(cli, ["--dry-run"])

        assert result.exit_code == 0
        assert "Host web-staging-nginx" in result.output
        assert "HostName 10.0.0.5" in result.output

    @patch("sync_ssh.get_cluster_service_ips")
    def test_dry_run_does_not_write_files(self, mock_get_ips, tmp_ssh_dir):
        mock_get_ips.return_value = {
            ("web-staging", "nginx"): ["10.0.0.5"]
        }
        hosts_path = tmp_ssh_dir / "ecs_hosts"
        runner = CliRunner()
        result = runner.invoke(
            cli, ["--dry-run", "--hosts-file", str(hosts_path)]
        )

        assert result.exit_code == 0
        assert not hosts_path.exists()


class TestCliWrite:
    @patch("sync_ssh.get_cluster_service_ips")
    def test_writes_hosts_file(self, mock_get_ips, tmp_ssh_dir):
        mock_get_ips.return_value = {
            ("web-staging", "nginx"): ["10.0.0.5"]
        }
        hosts_path = tmp_ssh_dir / "ecs_hosts"
        config_path = tmp_ssh_dir / "config"
        config_path.touch()

        runner = CliRunner()
        result = runner.invoke(
            cli,
            [
                "--hosts-file", str(hosts_path),
                "--ssh-config", str(config_path),
            ],
        )

        assert result.exit_code == 0
        content = hosts_path.read_text()
        assert "Host web-staging-nginx" in content
        assert "HostName 10.0.0.5" in content

    @patch("sync_ssh.get_cluster_service_ips")
    def test_updates_ssh_config_include(self, mock_get_ips, tmp_ssh_dir):
        mock_get_ips.return_value = {
            ("web-staging", "nginx"): ["10.0.0.5"]
        }
        hosts_path = tmp_ssh_dir / "ecs_hosts"
        config_path = tmp_ssh_dir / "config"
        config_path.write_text("Host old\n  HostName 1.1.1.1\n")

        runner = CliRunner()
        runner.invoke(
            cli,
            [
                "--hosts-file", str(hosts_path),
                "--ssh-config", str(config_path),
            ],
        )

        config_content = config_path.read_text()
        assert f"Include {hosts_path}" in config_content

    @patch("sync_ssh.get_cluster_service_ips")
    def test_identity_file_option(self, mock_get_ips, tmp_ssh_dir):
        mock_get_ips.return_value = {
            ("web", "app"): ["10.0.0.1"]
        }
        hosts_path = tmp_ssh_dir / "ecs_hosts"
        config_path = tmp_ssh_dir / "config"
        config_path.touch()

        runner = CliRunner()
        runner.invoke(
            cli,
            [
                "--hosts-file", str(hosts_path),
                "--ssh-config", str(config_path),
                "--identity-file", "~/.ssh/mykey.pem",
            ],
        )

        content = hosts_path.read_text()
        assert "IdentityFile ~/.ssh/mykey.pem" in content
